name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Apply patches
        run: ./patches/protonprep-valve-staging.sh &> patchlog.txt

      - name: Configure and Build
        run: |
          mkdir build && cd build
          ../configure.sh --build-name=Proton-fox
          make redist &> log

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: proton-fox-artifacts
          path: |
            build/Proton-fox.tar.gz
            build/Proton-fox.sha512sum
